main/urls.py
from django.urls import path
from . import views
from .views import Home,Tournaments,teamDetails,matchCreate,tournamentCreate,tournamentUpdate,userDetails,teamCreate, matchUpdate,matchDelete,serverDetails,searchTournament


urlpatterns = [
    path('',Home.as_view(),name='home'),
    path('tournaments/',Tournaments.as_view(),name='tournaments'),
    path('team/<int:pk>/',teamDetails.as_view(),name='team'),
    path('tournament/new/',tournamentCreate.as_view(),name='tournament-new'),
    path('tournament/<int:pk>/',views.tournamentDetails.as_view(),name='tournament'),
    path('tournament/<int:pk>/update/',views.tournamentUpdate.as_view(),name='tournament_update'),
    path('tournament/<int:id>/match/new/',matchCreate.as_view(),name = 'new_match'),
    path('tournament/<int:id>/match/<int:pk>/delete/',matchDelete.as_view(),name = 'delete_match'),
    path('user/<int:pk>/',userDetails.as_view(),name='user'),
    path('team/new/',teamCreate.as_view(),name = 'new_team'),
    path('tournament/<int:pk>/register/',views.register,name = 'register'),
    path('tournament/<int:pk>/feat/',views.temp,name='feat'),
    path('tournament/<int:pk>/random_matches/',views.test,name='random_matches'),
    path('tournament/<int:pk>/feat/',views.temp,name='feat'),
    path('tournament/<int:id>/match/<int:pk>/update/',matchUpdate.as_view(),name = 'tournament_update_match'),
    path('server/<int:pk>/',serverDetails.as_view(),name= 'server'),
    path('server/<int:pk>/start/',serverDetails.Start,name='server-start'),
    path('server/<int:pk>/stop/',serverDetails.Stop,name='server-stop'),
    path('server/<int:pk>/launchcs/',serverDetails.LaunchCS,name='server-launchcs'),
    path('server/<int:pk>/stopcs/',serverDetails.StopCS,name='server-stopcs'),
    path('server/<int:pk>/command/',serverDetails.CommandCS,name='server-command'),
    path('search/',searchTournament.as_view(),name='search'),
    path('tournament/<int:pk>/get_servers/',views.get_servers,name='get_servers'),
    path('tournament/<int:pk>/match/<int:id>/set_winner/',views.set_winner,name='set_winner'),
    path('tournament/<int:pk>/first_matches/',views.FirstMatches,name='first_matches'),
    path('tournament/<int:pk>/next_round/',views.next_round,name='next_round'),
    path('tournament/<int:pk>/match/<int:id>/set_server/',views.set_server,name='set_server'),



]

project/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),

    path('',include('login_signup.urls')),
    path('login/',include('login_signup.urls')),
    
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

main/models.py
from django.db import models
from login_signup import models as _
from django.contrib.postgres.fields import ArrayField
from django.urls import reverse
import boto3
from . import aws
ec2r = boto3.resource('ec2')
# Create your models here.

class Server(models.Model):
    aws_id = models.CharField(max_length=20, blank= True)
    ip = models.CharField(max_length=20, blank= False)
    port = models.IntegerField(null=False , default= 27015)
    is_assigned = models.BooleanField(default=False)
    

    def __str__(self):
        return f'{self.ip}:{self.port}'

    
    def state(self):
        return aws.ServerState(self.aws_id)


    def Startinstance(self):
        instance = aws.StartAserver(self.aws_id)
        return instance

    
    def Stopinstance(self):
        instance = aws.StopAserver(self.aws_id)
        return instance


    def LaunchCS(self):
        return aws.Start_cs(self.ip)

    
    def StopCS(self):
        return aws.Stop_cs(self.ip)

    
    def RestartCs(self):
        return aws.Restart_cs(self.ip)


    def SetIp(self):
        instance = ec2r.Instance(self.aws_id)
        self.ip = instance.public_ip_address
        self.save()
     
        return self.ip


    def Csstatus(self):
        if self.state() == 'running':
            return aws.Csstatus(self.ip)


    def get_absolute_url(self):
  
        return reverse("server", kwargs= {'pk': self.pk})


    def terminate(self):
        return aws.Terminate(self.aws_id)



class Team(models.Model):
    name = models.CharField(max_length=50,  null=False)
    tag = models.CharField(max_length=10, blank=True, null=True)
    logo = models.ImageField(upload_to="logos", blank=True, null=True)
    players = models.ManyToManyField(_.NewUser)
    team_description = models.CharField(max_length=150 , blank= True, null=True)
    player1 = models.CharField(max_length = 150, blank=True)
    player2 = models.CharField(max_length = 150, blank=True)
    player3 = models.CharField(max_length = 150, blank=True)
    player4 = models.CharField(max_length = 150, blank=True)
    player5 = models.CharField(max_length = 150, blank=True)



    def __str__(self):
        return self.name


    def get_absolute_url(self):
        print(reverse("team", kwargs= {'pk': self.pk}))
        return reverse("team", kwargs= {'pk': self.pk})


class Tournament(models.Model):
    name = models.CharField(max_length=50, blank=False, null=False)
    description = models.TextField(default = '')
    registration_starts = models.DateField(blank=False,null=False)
    registration_ends = models.DateField(blank=False,null=False)
    tournament_starts = models.DateField(blank=False,null=False)
    tournament_ends = models.DateField(blank=False,null=False)
    teams_left = models.ManyToManyField(Team,related_name= 'teams_left',blank=True,null=True)
    teams = models.ManyToManyField(Team,related_name= 'tournament_teams')
    banner = models.ImageField(upload_to="tournament_banners")
    logo = models.ImageField(upload_to="tournament_logo",default='../static/images/logo.png')
    organizer = models.ForeignKey(_.NewUser,on_delete=models.CASCADE)
    prizepool = models.IntegerField(blank=False,null=False)
    game = models.CharField(max_length=10, blank=True, null=True)
    contact_email = models.EmailField(max_length=254)
    contact_no = models.BigIntegerField(blank=False,null=True)
    sponsored_by = models.CharField(max_length=50, blank=True, null=True)
    is_feat = models.BooleanField(default=False)
    servers = models.ManyToManyField(Server,blank=True,null=True)
    winner = models.ForeignKey(Team, blank= True,null=True,on_delete=models.CASCADE,related_name='tournament_winner')
    


    def __str__(self):
        return self.name
    

    def get_absolute_url(self):
        print(reverse('tournament', kwargs= {'pk': self.pk}))
        return reverse('tournament', kwargs= {'pk': self.pk})




class Match(models.Model):
   

    server = models.ForeignKey(Server, on_delete= models.CASCADE, blank=True, null=True)

 
    stage = models.CharField(max_length = 50,blank=True, null=True)
    uuid = models.CharField(default='uuid4', max_length=100)
    
    team_1 = models.ForeignKey(
        Team, on_delete=models.SET_NULL, blank=True, null=True, related_name="team_1"
    )
    team_2 = models.ForeignKey(
        Team, on_delete=models.SET_NULL, blank=True, null=True, related_name="team_2"
    )
    
    winner = models.ForeignKey(
        Team, on_delete=models.SET_NULL, blank=True, null=True, related_name="winner"
    )
    status = models.CharField(max_length=50, default="Pending")
    start_time = models.DateTimeField(blank=True, null=True)
    end_time = models.DateTimeField(blank=True, null=True)
    skip_veto = models.BooleanField(default=True)
    team_1_score = models.IntegerField(default=0)
    team_2_score = models.IntegerField(default=0)
    veto_mappool = models.CharField(max_length=500, blank=True, null=True)
    match_map = models.CharField(max_length=20, blank=True, default='Default Dust2')
    max_maps = models.IntegerField(default=1)
    tournament = models.ManyToManyField(Tournament)

    class Meta:
        verbose_name = ("Match")
        verbose_name_plural = ("Matches")

    def teams(self):
        t1 = self.team_1

        t2 = self.team_2
        return f"{t1} vs {t2}"

    
    def setwinner(self,team):
        self.winner = team
        self.status = "DONE"
        self.save()

    
    @property
    def match_config(self) -> dict:
        t1_info = self.team_1.team_information if self.team_1 else {}
        t2_info = self.team_2.team_information if self.team_2 else {}
        return {
            "match_id": self.uuid,
            "num_maps": 1,
            "maplist": [{"de_dust2": ""}],
            "skip_veto": self.skip_veto,
            "veto_first": "team1",
            "side_type": "always_knife",
            "players_per_team": 5,
            "min_players_to_ready": 1,
            "team1": t1_info,
            "team2": t2_info,
            "cvars": {
                "hostname": f"Match - {t1_info.get('name')} vs {t2_info.get('name')}"
            },
        }
    
    def get_absolute_url(self):
    
  
        return reverse('home')

templates/Tournament_form.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colrolib Templates">
    <meta name="author" content="Colrolib">
    <meta name="keywords" content="Colrolib Templates">

    <!-- Title Page-->
    <title>tournament registration</title>

    <!-- Icons font CSS-->
    <link href="{% static '../static/vendor/mdi-font/css/material-design-iconic-font.min.css'%}" rel="stylesheet"
        media="all">
    <link href="{% static '../static/vendor/font-awesome-4.7/css/font-awesome.min.css'%}" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i"
        rel="stylesheet">
    <link
        href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="{% static '../static/vendor/select2/select2.min.css'%}" rel="stylesheet" media="all">
    <link href="{% static '../static/vendor/datepicker/daterangepicker.css'%}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static '../static/css/reg-main.css'%}" rel="stylesheet" media="all">
</head>
<style>
    ::placeholder{color:gray; opacity: 70%;}

</style>
<body>
    {% if user.is_organizer %}
    <div class="page-wrapper bg-img-3 p-t-240 p-b-120">
        <div class="wrapper wrapper--w900">
            <div class="card card-6">
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {%for message in messages%}
                        {{ message }}
						{% endfor %}
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Name</label>
                                    <div class="input--style-1">{{ form.name }}</div>

                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Game</label>
                                    <div class="input--style-1">{{ form.game }}</div>
                                </div>
                            </div>
                        </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Registration Starts</label>
                                    <div class="input--style-1" >{{ form.registration_starts }}</div>
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Registration Ends</label>
                                    <div class="input--style-1" >{{ form.registration_ends }}</div>
                                </div>
                            </div>
                        </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Tournament Starts</label>
                                    <div class="input--style-1" >{{ form.tournament_starts }}</div>
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Tournament Ends</label>
                                    <div class="input--style-1" >{{ form.tournament_ends}}</div>
                                </div>
                            </div>
                        </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <label class="label">Logo</label>
                                <div class="input-group-icon" id="js-select-special">
                                    <div class="input--style-1" >{{ form.logo }}</div>
                                </div>
                                
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Prizepool</label>
                                    <div class="input--style-1" >{{ form.prizepool }}</div>
                                </div>
                            </div>
                        </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Sponsored by</label>
                                    <div class="input--style-1" >{{ form.sponsored_by }}</div>
                                </div>
                                <div class="input-group">
                                    <label class="label">Contact No</label>
                                    <div class="input--style-1" >{{ form.contact_no }}</div>
                                </div>
                                <div class="input-group">
                                    <label class="label">Contact Email</label>
                                    <div class="input--style-1" >{{ form.contact_email }}</div>
                                </div>
                               
                            </div>
                            <div class="col-2">
                                <div class="input-group">

                                    <label class="label">Description</label>
                                    <div class="input--style-1">{{ form.description}}</div>
                                </div>
                            </div>


                        </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <label class="label">banner</label>
                                <div class="input-group-icon" id="js-select-special">
                                    <div class="input--style-1">{{ form.banner }}</div>
                                </div>

                            </div>

                            <div class="col-2">
                                <button class="btn-submit m-b-0" type="submit">Register</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Jquery JS-->
    <script src="{% static '../static/vendor/jquery/jquery.min.js'%}"></script>
    <!-- Vendor JS-->
    <script src="{% static '../static/vendor/select2/select2.min.js'%}"></script>
    <script src="{% static '../static/vendor/jquery-validate/jquery.validate.min.js'%}"></script>
    <script src="{% static '../static/vendor/bootstrap-wizard/bootstrap.min.js'%}"></script>
    <script src="{% static '../static/vendor/bootstrap-wizard/jquery.bootstrap.wizard.min.js'%}"></script>
    <script src="{% static '../static/vendor/datepicker/moment.min.js'%}"></script>
    <script src="{% static '../static/vendor/datepicker/daterangepicker.js'%}"></script>

    <!-- Main JS-->
    <script src="{% static '../static/js/global.js'%}"></script>
    {% endif %}
</body>

</html>
<!-- end document-->

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    

    <link rel="stylesheet" href="{% static '../static/css/style.css'%}">
    <link rel="stylesheet" href="{% static '../static/css/cards.css'%}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>{{ title }}</title>

</head>

<body>
    <haeder>
        <nav>
            <div class="logo">
                <a href="/"><img src="{% static '../static/images/logo.png'%}" height="60px" width="60px" alt=""></a>
                <h5>&nbsp;&nbsp;SouTM</h5>
            </div>
            <ul class="nav-links">
                <li><a href="/">Home</a></li>
                <li><a href="/tournaments/">Tournaments</a></li>
              
                {% if user.is_organizer %}
                {% if Hosted %}
                <li><a href="{% url 'tournament' tourna_id %}">Your Tournament</a></li>
                {% else %}
                <li><a href="/tournament/new">Host</a></li>
                {% endif %}
                {% else %}
                {% endif %}
             
                {% if user.is_authenticated %}
                <li><a href="{% url 'user' user.id %}">{{user.ign}}</a></li>
                <li><a href="/logout/">Logout</a></li>
                {% else %}
                <li><button type="button" onclick="location.href = '/login/'" class="button signin">Log in</button></li>
                <li><button type="button" onclick="location.href = '/signup/'" class="button signup">Sign up</button>
                </li>
                {% endif %}
            </ul>
            <div class="burger">
                <div class="line1"></div>
                <div class="line2"></div>
                <div class="line3"></div>
            </div>

        </nav>
        </header>

        {% block content %}
        {% endblock %}

        <script src="{% static '../static/js/app.js'%}"></script>
</body>

</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
<style>
  @media (max-width: 767px) {
 
    .csslider{
      width:70%;
      top:50px;
    
    }
    
  
    .csslider > .arrows label:before{
      height: 20px;
      width: 20px;
    }
    .csslider ul{
      width: 100%;
      
    }
    .csslider li{
      width: 100%;
      
    }
    .csslider h2{
      font-size: 20px;
    }
    .h4a{
     display:contents;
     letter-spacing: 2px;
    }
    .h4a h4{
      display: block;
      font-size: 2.5vw;
      text-decoration: none;
    }
    .csslider h2{
      
      font-size: 4.5vw;
      overflow-wrap: break-word;
    }
    .register{
      top:390px;

    }
  }

</style>
<main>
    <div class="csslider infinity" id="slider1">
        <input type="radio" name="slides" id="slides_1"/>
        <input type="radio" name="slides" checked="checked" id="slides_2"/>
        <input type="radio" name="slides" id="slides_3"/>
        <input type="radio" name="slides" id="slides_4"/>
        <input type="radio" name="slides" id="slides_5"/>
        <input type="radio" name="slides" id="slides_6"/>
        <ul>
          {% for tournament in tournaments %}
          <li>
            <img src="{{ tournament.logo.url }}" alt="" height="110px" width="110px" style="background: transparent;">
            
            <a href=" {% url 'tournament' tournament.id %}">
                <h2>{{ tournament.name }}</h2>
            </a>
            <div class="h4a" >
                <h4>Registration Starts:{{tournament.registration_starts }}</h4>
                <h4>Registration Ends: {{tournament.registration_ends}}</h4>
            </div>
            <br><br>
   
            {% if user.is_authenticated %}
            
            <button type="button" onclick="location.href = '/tournament/{{tournament.id}}/register/'" class="button register">Register</button>
            {% else %}
            <button type="button" onclick="location.href = '/login/'" class="button register">Register</button>
            
            {% endif %}

          </li>
          {% endfor %}
         
  
        </ul>
        <div class="arrows">
          {% for tournament in tournaments %}
          <label for="slides_{{ forloop.counter }}"></label>
          {% if forloop.counter == tournaments|length %}
          <label class="goto-first" for="slides_1"></label>
          <label class="goto-last" for="slides_{{forloop.counter}}"></label>
          {% endif %}
          {%endfor%}
        
          
    <label class="goto-first" for="slides_1"></label>
    <label class="goto-last" for="slides_6"></label>
          <!-- <label class="goto-first" for="slides_{{tournaments| length}}"></label>
          <label class="goto-last" for="slides_1"></label> -->
        </div>
        <div class="navigation"> 
          <div>
          {% for tournament in tournaments %}
          <label for="slides_{{loop.counter}}"></label>
          {%endfor%}
         
          </div>
        </div>
      </div>
</main>
{% endblock %}

templates/match_form.html
{% load crispy_forms_tags %}
{% block content %}
<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    * {
      box-sizing: border-box;
    }

    input[type=text],
    select,
    textarea {
      width: 100%;
      padding: 12px;
      border: 1px solid #ccc;
      border-radius: 4px;
      resize: vertical;
    }

    label {
      padding: 12px 12px 12px 0;
      display: inline-block;
    }

    input[type=submit] {
      background-color: #4CAF50;
      color: white;
      padding: 12px 20px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      float: right;
    }

    input[type=submit]:hover {
      background-color: #45a049;
    }

    .container {
      border-radius: 5px;
      background-color: #f2f2f2;
      padding: 20px;
    }

    .col-25 {
      float: left;
      width: 25%;
      margin-top: 6px;
    }

    .col-75 {
      float: left;
      width: 75%;
      margin-top: 6px;
    }

    /* Clear floats after the columns */
    .row:after {
      content: "";
      display: table;
      clear: both;
    }

    /* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
    @media screen and (max-width: 600px) {

      .col-25,
      .col-75,
      input[type=submit] {
        width: 100%;
        margin-top: 0;
      }
    }
  </style>
</head>

<body>

  <div class="container">
    <form method= "POST">
      {% csrf_token %}
      {{form}}
      <label for="team_1">Team 1</label>

      <select name="team_1" id="team_1">
        {% for team in teams %}
        <option value="{{team.id}}">{{ team }}</option>
        {% endfor %}
      </select>

      <label for="team_2">Team 2</label>

      <select name="team_2" id="team_2">
        {% for team in teams %}
        <option value="{{team.id}}">{{ team }}</option>
        {% endfor %}
      </select>

      <label for="server">Choose a server:</label>

      <select name="server" id="server">
        {% for server in servers %}
        <option value="{{server.id}}">{{ server }}</option>
        {% endfor %}
      </select>
      <br>
      <br>

      <div class="row">
        {% if update %}
        <a href="{% url 'delete_match' idd object.id %}" style="color: red;">Delete Match</a>
        {% endif%}
        <input type="submit" value="Submit">
      </div>
    </form>
  </div>

</body>

</html>

</div>
{% endblock %}

templates/nav.html
{% load static %}
{% block content %}
<nav>
   
    <div class="logo">
        <a href="/"><img src="{% static '../static/images/logo.png'%} " height="60px" width="60px" alt=""></a>
        <h5>&nbsp;&nbsp;SouTM</h5>
    </div>
    <ul class="nav-links">
        <li><a href="/">Home</a></li>
        <li><a href="/tournaments/">Tournaments</a></li>
       
     
        {% if user.is_authenticated %}
        <li><a href="#">{{user.ign}}</a></li>
        <li><a href="/logout/">Logout</a></li>
        {% else %}
        <li><button type="button" onclick="location.href = '/login/'" class="button signin">Log in</button></li>
        <li><button type="button" onclick="location.href = '/signup/'" class="button signup">Sign up</button>
        </li>
        {% endif %}
    </ul>
    <div class="burger">
        <div class="line1"></div>
        <div class="line2"></div>
        <div class="line3"></div>
    </div>

</nav>
{% endblock %}

templates/team_reg.html
{% extends 'base.html' %}

{% block content %}
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}


input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
  background: transparent;
}


input[type=submit] {
  background-color: #4CAF50;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  background: transparent;
}

input[type=submit]:hover {
  background-color: #45a049;
  background: transparent;
}
h1{

  background-color: transparent;
  font-family: sans-serif;

}
form{background: transparent;padding-top:120px;
width: 50%;}
label{background: transparent;}
input#id_logo{background: transparent;}
option{background: transparent;}
.container {
  position: inherit;
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;

}

</style>
</head>
<body>



<div class="container">

  <form method = "POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h1>Team Details</h1>
    <br>
    <label for="id_name">Team Name:</label>
    {{form.name}}
    <label for="id_tag">Team Tag:</label>
    {{form.tag}}
    <label for="id_team_description">Team Description:</label>
    {{form.team_description}}

    <label for="id_logo">Team Logo:&nbsp</label>
    {{form.logo}}
    <br><br><br>
    <h1>Player Details</h1>
    <br>
    <label for="player_1">Player 1:</label>
    <select style="background-color: transparent; color: white;" name="player_1" id="player_1">
      {% for player in players %}
      <option value="{{player.id}}">{{ player }}</option>
      {% endfor %}
  </select>
  <label for="id_player1">Player 1's steam id:</label>
    {{form.player1}}

  <label for="player_2">Player 2:</label>
  <select style="background-color: transparent; color: white;" name="player_2" id="player_2">
    {% for player in players %}
    <option value="{{player.id}}">{{ player }}</option>
    {% endfor %}
</select>
<label for="id_player2">Player 2's steam id:</label>
    {{form.player2}}
<label for="player_3">Player 3:</label>
<select style="background-color: transparent; color: white;" name="player_3" id="player_3">
  {% for player in players %}
  <option value="{{player.id}}">{{ player }}</option>
  {% endfor %}
</select>
<label for="id_player3">Player 3's steam id:</label>
    {{form.player3}}
<label for="player_4">Player 4:</label>
<select style="background-color: transparent; color: white;" name="player_4" id="player_4">
  {% for player in players %}
  <option value="{{player.id}}">{{ player }}</option>
  {% endfor %}
</select>
<label for="id_player4">Player 4's steam id:</label>
    {{form.player4}}
<label for="player_5">Player 5:</label>
<select style="background-color: transparent; color: white;" name="player_5" id="player_5">
  {% for player in players %}
  <option value="{{player.id}}">{{ player }}</option>
  {% endfor %}
</select>
<label for="id_player5">Player 5's steam id:</label>
{{form.player5}}

    
    <input type="submit" class = "button register" style = "position: inherit; background-color:#0A0E26;"value="Submit">
  </form>
</div>

{% endblock %}

templates/team_reg_players.html
{% extends 'base.html' %}

{% block content %}
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
  background: transparent;
}

input[type=submit] {
  background-color: #4CAF50;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  background: transparent;
}

input[type=submit]:hover {
  background-color: #45a049;
  background: transparent;
}
h1{

  background-color: transparent;
  font-family: sans-serif;

}
form{background: transparent;padding-top:280px;
width: 50%;}
label{background: transparent;}
input#id_logo{background: transparent;}
option{background: transparent;}
.container {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;

}

</style>
</head>
<body>



<div class="container">

  <form method = "POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h1>New Team</h1>
    <br>
    {{ form|linebreaksbr }}
    <select style="background-color: transparent; color: white;" name="player_1" id="player_1">
      {% for player in players %}
      <option value="{{player.id}}">{{ player }}</option>
      {% endfor %}
  </select>
    
    <input type="submit" class = "button register" style = "position: inherit; background-color:#0A0E26;"value="Next">
  </form>
</div>

{% endblock %}